import pytest

from aiactguard.plugins.registry import PluginRegistry


class _StubPlugin:
    def __init__(self, name: str):
        self.name = name
        self.description = f"stub {name}"

    def generate(self, logger, *, questionnaire=None, **kwargs):
        return f"generated by {self.name}"


class _FakeEntryPoint:
    def __init__(self, plugin):
        self._plugin = plugin

    def load(self):
        return self._plugin


def test_register_and_get():
    registry = PluginRegistry()
    plugin = _StubPlugin("gxp")
    registry.register(plugin)

    assert registry.get("gxp") is plugin
    assert registry.list_plugins() == ["gxp"]


def test_duplicate_registration_raises_without_overwrite():
    registry = PluginRegistry()
    registry.register(_StubPlugin("gxp"))

    with pytest.raises(ValueError):
        registry.register(_StubPlugin("gxp"))


def test_duplicate_registration_with_overwrite_replaces():
    registry = PluginRegistry()
    first = _StubPlugin("gxp")
    second = _StubPlugin("gxp")
    registry.register(first)
    registry.register(second, overwrite=True)

    assert registry.get("gxp") is second


def test_get_unknown_plugin_raises_key_error():
    registry = PluginRegistry()
    with pytest.raises(KeyError):
        registry.get("does_not_exist")


def test_discover_entry_points_registers_discovered_plugins(monkeypatch):
    registry = PluginRegistry()
    fake_plugin = _StubPlugin("discovered")

    def fake_entry_points(*, group):
        assert group == "aiactguard.plugins"
        return [_FakeEntryPoint(fake_plugin)]

    monkeypatch.setattr("aiactguard.plugins.registry.entry_points", fake_entry_points)

    discovered = registry.discover_entry_points()

    assert discovered == ["discovered"]
    assert registry.get("discovered") is fake_plugin
